export const footballFacts = [
  "Pelé is believed to have scored 1,281 goals in 1,363 career games.",
  "Brazil has won the FIFA World Cup a record 5 times.",
  "The fastest goal in football history was scored in just 2 seconds.",
  "Real Madrid has won the UEFA Champions League a record 15 times.",
  "The first World Cup was held in Uruguay in 1930.",
  "Lionel Messi scored 91 goals in a single calendar year in 2012, a record that still stands today.",
  "A regulation football match lasts 90 minutes plus stoppage time.",
  "The offside rule has been part of football since 1863.",
  "Ronaldo has scored over 800 career goals across club and country.",
  "The largest football stadium is Rungrado 1st of May in North Korea, holding 114,000 people.",
  "Barcelona's famous tiki-taka style was perfected under Pep Guardiola.",
  "Zinedine Zidane scored a volley in the 2002 Champions League final, widely considered the greatest goal ever.",
  "Jannik Sinner became the first Italian player in history to reach World No. 1 in June 2024.",
  "Carlos Alcaraz is the youngest man to ever reach World No. 1, achieving the feat at 19 years old.",
  "Tennis balls were originally white; they were changed to optic yellow in 1972 for better TV visibility.",
  "The longest tennis match in history lasted 11 hours and 5 minutes between John Isner and Nicolas Mahut.",
  "In 2024, Carlos Alcaraz won both the French Open and Wimbledon in the same calendar year.",
  "Jannik Sinner won his first Grand Slam title at the 2024 Australian Open after trailing by two sets.",
  "Rafael Nadal has won a record 14 French Open titles, the most by any player at a single major.",
  "Wimbledon is the only Grand Slam tournament that still requires players to wear almost entirely white clothing.",
  "The fastest serve ever recorded in a professional match was 163.7 mph (263.4 km/h) by Sam Groth.",
  "Novak Djokovic holds the record for the most weeks spent as World No. 1 in tennis history.",
  "A tennis match between Alcaraz and Sinner at the 2022 US Open ended at 2:50 AM, the latest finish in tournament history.",
  "The 'Golden Slam' (winning all 4 majors and Olympic Gold in one year) was achieved by Steffi Graf in 1988.",
  "Jannik Sinner is known for his 'Carota Boys' fan club, who dress up as carrots to support him.",
  "Carlos Alcaraz became the youngest player to defeat both Nadal and Djokovic in the same clay-court tournament.",
  "The term 'Love' in tennis scoring is thought to come from the French word 'l'oeuf,' meaning egg (zero).",
  "Yellow tennis balls were not used at Wimbledon until 1986.",
  "Roger Federer has won a record 8 Wimbledon men's singles titles.",
  "In 2025, Carlos Alcaraz became one of the youngest players to surpass $40 million in career prize money.",
  "Manchester United's Class of 92 produced Beckham, Scholes, Giggs, and the Neville brothers.",
  "AFCON — the Africa Cup of Nations — has been held since 1957.",
  "Lionel Messi has won a record 8 Ballon d'Or awards.",
  "The fastest red card in World Cup history was shown to José Batista after 56 seconds in 1986.",
  "Messi scored a record-breaking 91 goals in a single calendar year (2012).",
  "The 'Hand of God' goal was scored by Diego Maradona against England in 1986.",
  "Germany’s Miroslav Klose is the all-time top scorer in FIFA World Cup history with 16 goals.",
  "Lionel Messi spent 21 years at FC Barcelona before moving to PSG in 2021.",
  "The youngest player to ever play in a World Cup was Norman Whiteside at age 17.",
  "Messi holds the record for most goals scored in La Liga history (474).",
  "The first international football match was played between Scotland and England in 1872.",
  "Just Fontaine holds the record for most goals in a single World Cup tournament with 13.",
  "Messi is the only player to win the World Cup Golden Ball twice (2014 and 2022).",
  "Lamine Yamal is the youngest player to ever win a major international trophy, winning Euro 2024 at age 17.",
  "Lamine Yamal is the youngest goalscorer in La Liga history, netting his first goal at just 16 years and 87 days old.",
  "In 2007, a 20-year-old Lionel Messi famously bathed a 6-month-old Yamal for a charity calendar photoshoot.",
  "The 'Panenka' penalty is named after Antonín Panenka, who first used it in 1976.",
  "AC Milan’s Paolo Maldini played 647 matches for the club over 25 seasons.",
  "Messi won the 2008 Olympic gold medal with Argentina in Beijing.",
  "The fastest hat-trick in Premier League history was scored by Sadio Mané in 2 minutes 56 seconds.",
  "Messi is the most decorated player in football history with over 44 collective trophies.",
  "Goalkeeper Rogerio Ceni scored 131 goals in his career, mostly from free-kicks and penalties.",
  "The 'Maracanazo' refers to Uruguay’s shock 2-1 win over Brazil in the 1950 World Cup final.",
  "Messi provided the most assists in football history, surpassing 350 career assists.",
  "The Champions League anthem is based on George Frideric Handel's 'Zadok the Priest'.",
  "C. Ronaldo has scored 9 goals in 8 appearances against Bayern Munich in the UEFA Champions League. He is currently the player with the most goals against them in the competition's history.",
  "Messi's first professional contract with Barcelona was famously written on a paper napkin.",
  "Iceland is the smallest nation by population to ever qualify for a World Cup.",
  "The 1966 World Cup final is the only time England has won the tournament.",
  "A match between AS Adema and SO l'Emyrne in 2002 ended 149-0 (all own goals).",
  "Zlatan Ibrahimović has played for nine different clubs in the Champions League but has never won it.",
  "Messi scored five goals in a single Champions League match against Bayer Leverkusen in 2012.",
  "The 'Invincibles' refers to the 2003-04 Arsenal team that went an entire season undefeated.",
  `John Carpenter was the first person to win the top prize in the show "Who Wants to Be a Millionaire", doing so without using any of the three lifelines`
]